version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Test setup"
          shell: powershell.exe
          command: npm run setup
      - run:
          name: "Test setup"
          shell: bash.exe
          command: npm run setup
      - run:
          name: "Test setup"
          shell: cmd.exe
          command: npm run setup